apiVersion: v1
kind: ConfigMap
metadata:
  name: password
data:
  PW_KEY: PWVALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: account
data:
  ACC_KEY: cGFzc3dvcmQ=
type: Opaque

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  namespace: default
  labels:
    app: nginx
    backend: php
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: secrets-volume
  volumes:
  - name: secrets-volume
    secret:
      secretName: account
      items:
      - key: ACC_KEY
        path: shared.html

---
apiVersion: v1        
kind: Pod
metadata:
  name: nginx-pod-2
  namespace: default
  labels:
    app: nginx
    backend: php
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP 
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: config-volume
  volumes:
  - name: config-volume
    configMap:
      name: password
      items:
        - key: PW_KEY
          path: shared.html      

---
apiVersion: v1          
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: default
  labels:
    app: nginx
    backend: go
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    resources:
        requests:
            memory: "100Mi"
            cpu: "100m"
        limits:
            memory: "200Mi"
            cpu: "200m"    

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-svc
  name: nginx-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    backend: php
  type: NodePort

